package prune_test

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nnennandukwe/software-standards-bootstrap/internal/inventory"
	"github.com/nnennandukwe/software-standards-bootstrap/internal/prune"
	"github.com/nnennandukwe/software-standards-bootstrap/internal/workspace"
)

func TestBuildContextInventoriesAllRulesAndRepositorySkills(t *testing.T) {
	repo := lifecycleRepository(t)
	profile := capabilityProfile(t)
	provenance := filepath.Join(t.TempDir(), "provenance.yaml")
	writeFile(t, provenance, `schema: ssb.dev/artifact-provenance/v1
artifacts:
  - path: .software-standards/rules/keep-rule.md
    sha256: `+fileDigest(t, filepath.Join(repo, ".software-standards", "rules", "keep-rule.md"))+`
    origin: generated
    declaration: Generated by the adopted SSB workflow.
  - path: .agents/skills/orphan-skill/SKILL.md
    sha256: `+fileDigest(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "SKILL.md"))+`
    origin: user-authored
    declaration: Authored and adopted directly by the repository maintainer.
`)

	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	got, err := prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "review-one",
		Capabilities:    profile,
		Provenance:      provenance,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if got.Schema != prune.ContextSchema || got.ReviewID != "review-one" ||
		got.BaselineCommit != ws.Baseline() || got.ContextDigest == "" {
		t.Fatalf("unexpected context identity: %#v", got)
	}
	if len(got.Artifacts) != 2 {
		t.Fatalf("artifacts = %#v, want rule and unreferenced skill", got.Artifacts)
	}
	if got.Artifacts[0].Kind != prune.ArtifactSkill ||
		got.Artifacts[0].ID != "orphan-skill" ||
		got.Artifacts[0].Origin != prune.OriginUserAuthored {
		t.Fatalf("unexpected skill artifact: %#v", got.Artifacts[0])
	}
	if got.Artifacts[1].Kind != prune.ArtifactRule ||
		got.Artifacts[1].ID != "keep-rule" ||
		got.Artifacts[1].Origin != prune.OriginGenerated {
		t.Fatalf("unexpected rule artifact: %#v", got.Artifacts[1])
	}
	if len(got.Capabilities.Capabilities) != 1 ||
		got.Capabilities.Capabilities[0].Status != prune.CapabilitySupported {
		t.Fatalf("unexpected capability profile: %#v", got.Capabilities)
	}
}

func TestBuildContextFailsClosedOnIncompleteInventory(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:     "review-one",
		Capabilities: capabilityProfile(t),
		InventoryLimits: inventory.Limits{
			MaxCandidateFiles: 1,
			MaxCandidateBytes: 1 << 20,
			MaxFileBytes:      1 << 20,
		},
	})
	if err == nil || !strings.Contains(err.Error(), "inventory coverage incomplete") {
		t.Fatalf("error = %v, want incomplete-coverage block", err)
	}
}

func TestBuildContextFailsClosedWhenSkillSupportExceedsInventoryBoundary(t *testing.T) {
	repo := lifecycleRepository(t)
	writeFile(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "assets", "large.txt"), strings.Repeat("x", 2048))
	git(t, repo, "add", ".agents/skills/orphan-skill")
	git(t, repo, "commit", "-m", "add oversized skill support")
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:     "review-one",
		Capabilities: capabilityProfile(t),
		InventoryLimits: inventory.Limits{
			MaxCandidateFiles: 100,
			MaxCandidateBytes: 1 << 20,
			MaxFileBytes:      1024,
		},
	})
	if err == nil || !strings.Contains(err.Error(), "excluded from the bounded inventory") {
		t.Fatalf("error = %v, want bounded skill-support failure", err)
	}
}

func TestBuildContextMarksMissingProvenanceUnknown(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	got, err := prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "review-one",
		Capabilities:    capabilityProfile(t),
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, artifact := range got.Artifacts {
		if artifact.Origin != prune.OriginUnknown {
			t.Fatalf("artifact inferred provenance: %#v", artifact)
		}
	}
}

func TestValidateProposalRequiresCompleteNonOverlappingActions(t *testing.T) {
	context := prune.Context{
		Schema:        prune.ContextSchema,
		ReviewID:      "review-one",
		ContextDigest: "sha256:" + strings.Repeat("1", 64),
		Inventory: inventory.Report{Files: []inventory.File{{
			Path: "README.md", Lines: 1, SHA256: "sha256:" + strings.Repeat("4", 64),
		}}},
		Artifacts: []prune.Artifact{
			{
				Kind:   prune.ArtifactRule,
				ID:     "keep-rule",
				Path:   ".software-standards/rules/keep-rule.md",
				SHA256: "sha256:" + strings.Repeat("2", 64),
				Origin: prune.OriginGenerated,
			},
			{
				Kind:   prune.ArtifactSkill,
				ID:     "orphan-skill",
				Path:   ".agents/skills/orphan-skill/SKILL.md",
				SHA256: "sha256:" + strings.Repeat("3", 64),
				Origin: prune.OriginUserAuthored,
			},
		},
		Capabilities: prune.CapabilityProfile{
			Capabilities: []prune.Capability{{
				ID:          "agent-skills-discovery",
				Status:      prune.CapabilitySupported,
				EvidenceIDs: []string{"host-run"},
			}},
		},
	}
	proposal := prune.Proposal{
		Schema:        prune.ProposalSchema,
		ReviewID:      "review-one",
		ContextDigest: context.ContextDigest,
		Actions: []prune.Action{{
			ID:          "keep-rule",
			Disposition: prune.DispositionKeep,
			Sources:     []prune.ArtifactRef{prune.Reference(context.Artifacts[0])},
			Rationale:   "Repository and host evidence still support this rule.",
			Confidence:  prune.ConfidenceHigh,
			RepositoryEvidence: []prune.EvidenceRef{{
				Path:   "README.md",
				Lines:  "1-1",
				SHA256: "sha256:" + strings.Repeat("4", 64),
			}},
			CapabilityRefs: []string{"agent-skills-discovery"},
			RequiredVerification: []prune.CheckRequirement{{
				ID: "review-check", Command: "ssb validate --repo .",
			}},
		}},
	}

	diagnostics := prune.ValidateProposal(context, proposal, t.TempDir())
	if len(diagnostics) != 1 ||
		!strings.Contains(diagnostics[0].Message, "orphan-skill") {
		t.Fatalf("diagnostics = %#v, want uncovered skill", diagnostics)
	}
}

func TestValidateProposalForcesUnknownProvenanceToUnableToDetermine(t *testing.T) {
	context := prune.Context{
		Schema:        prune.ContextSchema,
		ReviewID:      "review-one",
		ContextDigest: "sha256:" + strings.Repeat("1", 64),
		Inventory: inventory.Report{Files: []inventory.File{{
			Path: "README.md", Lines: 1, SHA256: "sha256:" + strings.Repeat("4", 64),
		}}},
		Artifacts: []prune.Artifact{{
			Kind:   prune.ArtifactRule,
			ID:     "unknown-rule",
			Path:   ".software-standards/rules/unknown-rule.md",
			SHA256: "sha256:" + strings.Repeat("2", 64),
			Origin: prune.OriginUnknown,
		}},
		Capabilities: prune.CapabilityProfile{
			Capabilities: []prune.Capability{{
				ID:          "agent-rules",
				Status:      prune.CapabilitySupported,
				EvidenceIDs: []string{"host-run"},
			}},
		},
	}
	action := prune.Action{
		ID:          "remove-unknown",
		Disposition: prune.DispositionRemove,
		Sources:     []prune.ArtifactRef{prune.Reference(context.Artifacts[0])},
		Rationale:   "The capability evidence suggests this is redundant.",
		Confidence:  prune.ConfidenceMedium,
		RepositoryEvidence: []prune.EvidenceRef{{
			Path:   "README.md",
			Lines:  "1-1",
			SHA256: "sha256:" + strings.Repeat("4", 64),
		}},
		CapabilityRefs: []string{"agent-rules"},
		RequiredVerification: []prune.CheckRequirement{{
			ID: "review-check", Command: "ssb validate --repo .",
		}},
	}
	proposal := prune.Proposal{
		Schema:        prune.ProposalSchema,
		ReviewID:      context.ReviewID,
		ContextDigest: context.ContextDigest,
		Actions:       []prune.Action{action},
	}

	diagnostics := prune.ValidateProposal(context, proposal, t.TempDir())
	if len(diagnostics) == 0 ||
		!strings.Contains(diagnostics[0].Message, "unable-to-determine") {
		t.Fatalf("diagnostics = %#v, want provenance block", diagnostics)
	}

	proposal.Actions[0].Disposition = prune.DispositionUnableToDetermine
	proposal.Actions[0].CapabilityRefs = nil
	proposal.Actions[0].RepositoryEvidence = nil
	proposal.Actions[0].UnresolvedQuestions = []string{"Who authored and adopted this rule?"}
	if diagnostics := prune.ValidateProposal(context, proposal, t.TempDir()); len(diagnostics) != 0 {
		t.Fatalf("unable-to-determine proposal rejected: %#v", diagnostics)
	}
}

func lifecycleRepository(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	git(t, repo, "init", "-b", "main")
	writeFile(t, filepath.Join(repo, "README.md"), "fixture\n")
	git(t, repo, "add", "README.md")
	git(t, repo, "commit", "-m", "baseline")
	baseline := strings.TrimSpace(git(t, repo, "rev-parse", "HEAD"))
	writeFile(t, filepath.Join(repo, ".software-standards", "assessment.md"), "assessment\n")
	writeFile(t, filepath.Join(repo, ".software-standards", "rules", "keep-rule.md"), fmt.Sprintf(`---
schema: ssb.dev/rule/v2
id: keep-rule
title: Keep the rule
topic: maintainability
lenses:
  - kind: base
directive: prefer
scopes:
  - "**"
classification: guidance
importance: high
score:
  method: ssb-score-v1
  total: 70
  factors:
    prevalence: 15
    consistency: 15
    authority: 15
    risk: 15
    applicability: 10
confidence: high
baseline_commit: %s
evidence:
  - path: README.md
    lines: 1-1
    excerpt_sha256: %s
    authoritative: true
verification:
  proof_gap: No deterministic repository check covers this guidance.
---
Keep the rule.
`, baseline, fileDigest(t, filepath.Join(repo, "README.md"))))
	writeFile(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "SKILL.md"), `---
name: orphan-skill
description: A repository-authored skill that is not referenced by a rule.
metadata:
  topic: maintainability
---
Follow the workflow.
`)
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "adopt standards")
	return repo
}

func capabilityProfile(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	evidencePath := filepath.Join(dir, "host-run.json")
	writeFile(t, evidencePath, `{"result":"supported"}`+"\n")
	profilePath := filepath.Join(dir, "capabilities.yaml")
	writeFile(t, profilePath, `schema: ssb.dev/capability-profile/v1
id: codex-example
host:
  name: codex
  version: 1.2.3
model:
  provider: openai
  id: gpt-example
observed_at: 2026-07-27T18:00:00Z
evidence:
  - id: host-run
    kind: conformance
    path: host-run.json
    sha256: `+fileDigest(t, evidencePath)+`
capabilities:
  - id: agent-skills-discovery
    status: supported
    evidence_ids:
      - host-run
`)
	return profilePath
}

func fileDigest(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func git(t *testing.T, dir string, args ...string) string {
	t.Helper()
	base := []string{"-c", "user.name=SSB Test", "-c", "user.email=ssb@example.invalid", "-C", dir}
	command := exec.Command("git", append(base, args...)...)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
