package prune_test

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/nnennandukwe/software-standards-bootstrap/internal/inventory"
	"github.com/nnennandukwe/software-standards-bootstrap/internal/prune"
	"github.com/nnennandukwe/software-standards-bootstrap/internal/workspace"
)

func TestBuildContextInventoriesAllRulesAndRepositorySkills(t *testing.T) {
	repo := lifecycleRepository(t)
	profile := capabilityProfile(t)
	provenance := filepath.Join(t.TempDir(), "provenance.yaml")
	writeFile(t, provenance, `schema: ssb.dev/artifact-provenance/v1
artifacts:
  - path: .software-standards/rules/keep-rule.md
    sha256: `+fileDigest(t, filepath.Join(repo, ".software-standards", "rules", "keep-rule.md"))+`
    origin: generated
    declaration: Generated by the adopted SSB workflow.
  - path: .agents/skills/orphan-skill/SKILL.md
    sha256: `+fileDigest(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "SKILL.md"))+`
    origin: user-authored
    declaration: Authored and adopted directly by the repository maintainer.
`)

	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	got, err := prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "review-one",
		Capabilities:    profile,
		Provenance:      provenance,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err != nil {
		t.Fatal(err)
	}
	if got.Schema != prune.ContextSchema || got.ReviewID != "review-one" ||
		got.BaselineCommit != ws.Baseline() || got.ContextDigest == "" {
		t.Fatalf("unexpected context identity: %#v", got)
	}
	if len(got.Artifacts) != 2 {
		t.Fatalf("artifacts = %#v, want rule and unreferenced skill", got.Artifacts)
	}
	if got.Artifacts[0].Kind != prune.ArtifactSkill ||
		got.Artifacts[0].ID != "orphan-skill" ||
		got.Artifacts[0].Origin != prune.OriginUserAuthored {
		t.Fatalf("unexpected skill artifact: %#v", got.Artifacts[0])
	}
	if got.Artifacts[1].Kind != prune.ArtifactRule ||
		got.Artifacts[1].ID != "keep-rule" ||
		got.Artifacts[1].Origin != prune.OriginGenerated {
		t.Fatalf("unexpected rule artifact: %#v", got.Artifacts[1])
	}
	if len(got.Capabilities.Capabilities) != 1 ||
		got.Capabilities.Capabilities[0].Status != prune.CapabilitySupported {
		t.Fatalf("unexpected capability profile: %#v", got.Capabilities)
	}
}

func TestBuildContextFailsClosedOnIncompleteInventory(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:     "review-one",
		Capabilities: capabilityProfile(t),
		InventoryLimits: inventory.Limits{
			MaxCandidateFiles: 1,
			MaxCandidateBytes: 1 << 20,
			MaxFileBytes:      1 << 20,
		},
	})
	if err == nil || !strings.Contains(err.Error(), "inventory coverage incomplete") {
		t.Fatalf("error = %v, want incomplete-coverage block", err)
	}
}

func TestBuildContextRejectsBackslashCapabilityEvidenceBeforeRead(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}

	profileDir := t.TempDir()
	outsideEvidence := filepath.Join(filepath.Dir(profileDir), "outside.json")
	writeFile(t, outsideEvidence, "{\"supported\":true}\n")
	profilePath := filepath.Join(profileDir, "capabilities.yaml")
	writeFile(t, profilePath, `schema: ssb.dev/capability-profile/v1
id: unsafe-path
host: {name: codex, version: 1.2.3}
model: {provider: openai, id: gpt-example}
observed_at: 2026-07-27T18:00:00Z
evidence:
  - id: host-run
    kind: conformance
    path: ..\outside.json
    sha256: `+fileDigest(t, outsideEvidence)+`
capabilities:
  - id: repository-instructions
    status: supported
    evidence_ids: [host-run]
`)

	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "unsafe-path",
		Capabilities:    profilePath,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err == nil || !strings.Contains(err.Error(), "unsafe capability evidence path") {
		t.Fatalf("error = %v, want unsafe capability evidence path", err)
	}
}

func TestBuildContextRejectsSymlinkedCapabilityEvidenceBeforeRead(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}

	profileDir := t.TempDir()
	outsideEvidence := filepath.Join(filepath.Dir(profileDir), "outside-symlink-evidence.json")
	writeFile(t, outsideEvidence, "{\"supported\":true}\n")
	evidencePath := filepath.Join(profileDir, "host-run.json")
	if err := os.Symlink(outsideEvidence, evidencePath); err != nil {
		t.Skipf("symlinks are unavailable: %v", err)
	}
	profilePath := filepath.Join(profileDir, "capabilities.yaml")
	writeFile(t, profilePath, `schema: ssb.dev/capability-profile/v1
id: unsafe-symlink
host: {name: codex, version: 1.2.3}
model: {provider: openai, id: gpt-example}
observed_at: 2026-07-27T18:00:00Z
evidence:
  - id: host-run
    kind: conformance
    path: host-run.json
    sha256: `+fileDigest(t, outsideEvidence)+`
capabilities:
  - id: repository-instructions
    status: supported
    evidence_ids: [host-run]
`)

	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "unsafe-symlink",
		Capabilities:    profilePath,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err == nil || !strings.Contains(err.Error(), "path contains a symlink") {
		t.Fatalf("error = %v, want symlinked capability evidence block", err)
	}
}

func TestBuildContextAcceptsRelativeCapabilityProfile(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	profile := capabilityProfile(t)
	t.Chdir(filepath.Dir(profile))

	if _, err := prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "relative-profile",
		Capabilities:    filepath.Base(profile),
		InventoryLimits: inventory.DefaultLimits(),
	}); err != nil {
		t.Fatalf("relative capability profile rejected: %v", err)
	}
}

func TestBuildContextRejectsDuplicateCapabilityEvidencePath(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	profileDir := t.TempDir()
	evidencePath := filepath.Join(profileDir, "host-run.json")
	writeFile(t, evidencePath, "{\"supported\":true}\n")
	profilePath := filepath.Join(profileDir, "capabilities.yaml")
	writeFile(t, profilePath, `schema: ssb.dev/capability-profile/v1
id: duplicate-evidence
host: {name: codex, version: 1.2.3}
model: {provider: openai, id: gpt-example}
observed_at: 2026-07-27T18:00:00Z
evidence:
  - id: host-run
    kind: conformance
    path: host-run.json
    sha256: `+fileDigest(t, evidencePath)+`
  - id: host-run-again
    kind: conformance
    path: host-run.json
    sha256: `+fileDigest(t, evidencePath)+`
capabilities:
  - id: repository-instructions
    status: supported
    evidence_ids: [host-run]
`)

	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "duplicate-evidence",
		Capabilities:    profilePath,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err == nil || !strings.Contains(err.Error(), "duplicate capability evidence path") {
		t.Fatalf("error = %v, want duplicate evidence path rejection", err)
	}
}

func TestBuildContextRejectsNonPortableTrackedSkillSupport(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Windows cannot create the POSIX-only baseline fixture")
	}
	repo := lifecycleRepository(t)
	writeFile(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "CON"), "support\n")
	git(t, repo, "add", ".agents/skills/orphan-skill/CON")
	git(t, repo, "commit", "-m", "add non-portable support")
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "non-portable-baseline",
		Capabilities:    capabilityProfile(t),
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err == nil || !strings.Contains(err.Error(), "non-portable governed path") {
		t.Fatalf("error = %v, want non-portable baseline block", err)
	}
}

func TestBuildContextFailsClosedWhenSkillSupportExceedsInventoryBoundary(t *testing.T) {
	repo := lifecycleRepository(t)
	writeFile(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "assets", "large.txt"), strings.Repeat("x", 2048))
	git(t, repo, "add", ".agents/skills/orphan-skill")
	git(t, repo, "commit", "-m", "add oversized skill support")
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	_, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:     "review-one",
		Capabilities: capabilityProfile(t),
		InventoryLimits: inventory.Limits{
			MaxCandidateFiles: 100,
			MaxCandidateBytes: 1 << 20,
			MaxFileBytes:      1024,
		},
	})
	if err == nil || !strings.Contains(err.Error(), "excluded from the bounded inventory") {
		t.Fatalf("error = %v, want bounded skill-support failure", err)
	}
}

func TestBuildContextMarksMissingProvenanceUnknown(t *testing.T) {
	repo := lifecycleRepository(t)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	got, err := prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "review-one",
		Capabilities:    capabilityProfile(t),
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, artifact := range got.Artifacts {
		if artifact.Origin != prune.OriginUnknown {
			t.Fatalf("artifact inferred provenance: %#v", artifact)
		}
	}
}

func TestBuildContextRequiresProvenanceForEverySkillBundleFile(t *testing.T) {
	repo := lifecycleRepository(t)
	supportPath := filepath.Join(repo, ".agents", "skills", "orphan-skill", "scripts", "check.sh")
	writeFile(t, supportPath, "#!/bin/sh\nexit 0\n")
	git(t, repo, "add", ".agents/skills/orphan-skill/scripts/check.sh")
	git(t, repo, "commit", "-m", "add skill support")

	entryPath := filepath.Join(repo, ".agents", "skills", "orphan-skill", "SKILL.md")
	provenance := filepath.Join(t.TempDir(), "provenance.yaml")
	writeFile(t, provenance, `schema: ssb.dev/artifact-provenance/v1
artifacts:
  - path: .agents/skills/orphan-skill/SKILL.md
    sha256: `+fileDigest(t, entryPath)+`
    origin: generated
    declaration: Generated before the supporting script was added.
`)
	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	got, err := prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "partial-provenance",
		Capabilities:    capabilityProfile(t),
		Provenance:      provenance,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, artifact := range got.Artifacts {
		if artifact.ID == "orphan-skill" {
			if artifact.Origin != prune.OriginUnknown {
				t.Fatalf("skill origin = %q, want unknown for partially declared bundle", artifact.Origin)
			}
			found = true
		}
	}
	if !found {
		t.Fatal("orphan-skill artifact is missing")
	}

	writeFile(t, provenance, `schema: ssb.dev/artifact-provenance/v1
artifacts:
  - path: .agents/skills/orphan-skill/SKILL.md
    sha256: `+fileDigest(t, entryPath)+`
    origin: generated
    declaration: Generated entrypoint.
  - path: .agents/skills/orphan-skill/scripts/check.sh
    sha256: `+fileDigest(t, supportPath)+`
    origin: user-authored
    declaration: Maintainer-authored supporting script.
`)
	got, err = prune.BuildContext(context.Background(), ws, prune.ContextOptions{
		ReviewID:        "mixed-provenance",
		Capabilities:    capabilityProfile(t),
		Provenance:      provenance,
		InventoryLimits: inventory.DefaultLimits(),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, artifact := range got.Artifacts {
		if artifact.ID == "orphan-skill" && artifact.Origin != prune.OriginMixed {
			t.Fatalf("skill origin = %q, want mixed for differently authored bundle files", artifact.Origin)
		}
	}
}

func TestValidateProposalRequiresCompleteNonOverlappingActions(t *testing.T) {
	context := prune.Context{
		Schema:        prune.ContextSchema,
		ReviewID:      "review-one",
		ContextDigest: "sha256:" + strings.Repeat("1", 64),
		Inventory: inventory.Report{Files: []inventory.File{{
			Path: "README.md", Lines: 1, SHA256: "sha256:" + strings.Repeat("4", 64),
		}}},
		Artifacts: []prune.Artifact{
			{
				Kind:   prune.ArtifactRule,
				ID:     "keep-rule",
				Path:   ".software-standards/rules/keep-rule.md",
				SHA256: "sha256:" + strings.Repeat("2", 64),
				Origin: prune.OriginGenerated,
			},
			{
				Kind:   prune.ArtifactSkill,
				ID:     "orphan-skill",
				Path:   ".agents/skills/orphan-skill/SKILL.md",
				SHA256: "sha256:" + strings.Repeat("3", 64),
				Origin: prune.OriginUserAuthored,
			},
		},
		Capabilities: prune.CapabilityProfile{
			Capabilities: []prune.Capability{{
				ID:          "agent-skills-discovery",
				Status:      prune.CapabilitySupported,
				EvidenceIDs: []string{"host-run"},
			}},
		},
	}
	proposal := prune.Proposal{
		Schema:        prune.ProposalSchema,
		ReviewID:      "review-one",
		ContextDigest: context.ContextDigest,
		Actions: []prune.Action{{
			ID:          "keep-rule",
			Disposition: prune.DispositionKeep,
			Sources:     []prune.ArtifactRef{artifactReference(context.Artifacts[0])},
			Rationale:   "Repository and host evidence still support this rule.",
			Confidence:  prune.ConfidenceHigh,
			RepositoryEvidence: []prune.EvidenceRef{{
				Path:   "README.md",
				Lines:  "1-1",
				SHA256: "sha256:" + strings.Repeat("4", 64),
			}},
			CapabilityRefs: []string{"agent-skills-discovery"},
			RequiredVerification: []prune.CheckRequirement{{
				ID: "review-check", Command: "ssb validate --repo .",
			}},
		}},
	}

	diagnostics := prune.ValidateProposal(context, proposal, t.TempDir())
	if len(diagnostics) != 1 ||
		!strings.Contains(diagnostics[0].Message, "orphan-skill") {
		t.Fatalf("diagnostics = %#v, want uncovered skill", diagnostics)
	}
}

func TestValidateProposalForcesUnknownProvenanceToUnableToDetermine(t *testing.T) {
	context := prune.Context{
		Schema:        prune.ContextSchema,
		ReviewID:      "review-one",
		ContextDigest: "sha256:" + strings.Repeat("1", 64),
		Inventory: inventory.Report{Files: []inventory.File{{
			Path: "README.md", Lines: 1, SHA256: "sha256:" + strings.Repeat("4", 64),
		}}},
		Artifacts: []prune.Artifact{{
			Kind:   prune.ArtifactRule,
			ID:     "unknown-rule",
			Path:   ".software-standards/rules/unknown-rule.md",
			SHA256: "sha256:" + strings.Repeat("2", 64),
			Origin: prune.OriginUnknown,
		}},
		Capabilities: prune.CapabilityProfile{
			Capabilities: []prune.Capability{{
				ID:          "agent-rules",
				Status:      prune.CapabilitySupported,
				EvidenceIDs: []string{"host-run"},
			}},
		},
	}
	action := prune.Action{
		ID:          "remove-unknown",
		Disposition: prune.DispositionRemove,
		Sources:     []prune.ArtifactRef{artifactReference(context.Artifacts[0])},
		Rationale:   "The capability evidence suggests this is redundant.",
		Confidence:  prune.ConfidenceMedium,
		RepositoryEvidence: []prune.EvidenceRef{{
			Path:   "README.md",
			Lines:  "1-1",
			SHA256: "sha256:" + strings.Repeat("4", 64),
		}},
		CapabilityRefs: []string{"agent-rules"},
		RequiredVerification: []prune.CheckRequirement{{
			ID: "review-check", Command: "ssb validate --repo .",
		}},
	}
	proposal := prune.Proposal{
		Schema:        prune.ProposalSchema,
		ReviewID:      context.ReviewID,
		ContextDigest: context.ContextDigest,
		Actions:       []prune.Action{action},
	}

	diagnostics := prune.ValidateProposal(context, proposal, t.TempDir())
	if len(diagnostics) == 0 ||
		!strings.Contains(diagnostics[0].Message, "unable-to-determine") {
		t.Fatalf("diagnostics = %#v, want provenance block", diagnostics)
	}

	proposal.Actions[0].Disposition = prune.DispositionUnableToDetermine
	proposal.Actions[0].CapabilityRefs = nil
	proposal.Actions[0].RepositoryEvidence = nil
	proposal.Actions[0].UnresolvedQuestions = []string{"Who authored and adopted this rule?"}
	if diagnostics := prune.ValidateProposal(context, proposal, t.TempDir()); len(diagnostics) == 0 ||
		!strings.Contains(diagnostics[0].Message, "structured evidence gap") {
		t.Fatalf("diagnostics = %#v, want structured evidence gap requirement", diagnostics)
	}
	proposal.Actions[0].EvidenceGaps = []prune.EvidenceGap{{
		Kind:         prune.EvidenceGapProvenance,
		ArtifactPath: context.Artifacts[0].Path,
		Detail:       "No provenance declaration matches the inventoried rule bytes.",
	}}
	if diagnostics := prune.ValidateProposal(context, proposal, t.TempDir()); len(diagnostics) != 0 {
		t.Fatalf("evidence-bound unable-to-determine proposal rejected: %#v", diagnostics)
	}
}

func lifecycleRepository(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	git(t, repo, "init", "-b", "main")
	writeFile(t, filepath.Join(repo, "README.md"), "fixture\n")
	git(t, repo, "add", "README.md")
	git(t, repo, "commit", "-m", "baseline")
	baseline := strings.TrimSpace(git(t, repo, "rev-parse", "HEAD"))
	evidenceDigest := fileDigest(t, filepath.Join(repo, "README.md"))
	evidenceOID := strings.TrimSpace(git(t, repo, "rev-parse", baseline+":README.md"))
	writeFile(t, filepath.Join(repo, ".software-standards", "report.md"), fmt.Sprintf(`---
schema: ssb.dev/report/v1
baseline_commit: %s
inventory:
  schema_version: 2
  inventory_version: ssb-inventory-v2
  baseline_commit: %s
  limits:
    max_candidate_files: 40000
    max_candidate_bytes: 134217728
    max_file_bytes: 1048576
  candidate_files: 1
  candidate_bytes: 8
  scanned_files: 1
  scanned_bytes: 8
  indexed_files: 1
  indexed_bytes: 8
  files:
    - path: README.md
      blob_oid: "%s"
      bytes: 8
      lines: 1
      language: Markdown
      sha256: %s
  excluded:
    binary: 0
    generated: 0
    oversized: 0
    secret_like: 0
    symlink: 0
    submodule: 0
    vendor_or_generated_tree: 0
    non_regular: 0
  truncated: false
  remaining_candidate_files: 0
  remaining_candidate_bytes: 0
artifacts:
  - id: keep-rule
    kind: rule
    path: .software-standards/rules/keep-rule.md
    confidence: high
    utility:
      method: ssb-utility-v1
      total: 70
      factors:
        marginal_value: 20
        risk_reduction: 15
        actionability: 15
        applicability: 10
        earlier_feedback: 10
  - id: orphan-skill
    kind: skill
    path: .agents/skills/orphan-skill/SKILL.md
    confidence: medium
    utility:
      method: ssb-utility-v1
      total: 50
      factors:
        marginal_value: 15
        risk_reduction: 10
        actionability: 10
        applicability: 10
        earlier_feedback: 5
    category: maintainability
    lenses:
      - kind: base
    scopes:
      - "**"
    derivation: extracted
    evidence:
      - role: declares
        path: README.md
        lines: 1-1
        excerpt_sha256: %s
---
# Software standards report

The accepted rule and procedural skill were derived from complete baseline inventory.
`, baseline, baseline, evidenceOID, evidenceDigest, evidenceDigest))
	writeFile(t, filepath.Join(repo, ".software-standards", "rules", "keep-rule.md"), fmt.Sprintf(`---
schema: ssb.dev/rule/v2
id: keep-rule
title: Keep the rule
category: maintainability
lenses:
  - kind: base
directive: prefer
scopes:
  - "**"
derivation: extracted
evidence:
  - role: declares
    path: README.md
    lines: 1-1
    excerpt_sha256: %s
---
Keep the rule.
`, evidenceDigest))
	writeFile(t, filepath.Join(repo, ".agents", "skills", "orphan-skill", "SKILL.md"), `---
name: orphan-skill
description: A repository-authored skill that is not referenced by a rule.
metadata:
  category: maintainability
---
Follow the workflow.
`)
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "adopt standards")
	return repo
}

func capabilityProfile(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	evidencePath := filepath.Join(dir, "host-run.json")
	writeFile(t, evidencePath, `{"result":"supported"}`+"\n")
	profilePath := filepath.Join(dir, "capabilities.yaml")
	writeFile(t, profilePath, `schema: ssb.dev/capability-profile/v1
id: codex-example
host:
  name: codex
  version: 1.2.3
model:
  provider: openai
  id: gpt-example
observed_at: 2026-07-27T18:00:00Z
evidence:
  - id: host-run
    kind: conformance
    path: host-run.json
    sha256: `+fileDigest(t, evidencePath)+`
capabilities:
  - id: agent-skills-discovery
    status: supported
    evidence_ids:
      - host-run
`)
	return profilePath
}

func fileDigest(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(data)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func artifactReference(artifact prune.Artifact) prune.ArtifactRef {
	return prune.ArtifactRef{
		Kind:   artifact.Kind,
		ID:     artifact.ID,
		Path:   artifact.Path,
		SHA256: artifact.SHA256,
	}
}

func git(t *testing.T, dir string, args ...string) string {
	t.Helper()
	base := []string{"-c", "user.name=SSB Test", "-c", "user.email=ssb@example.invalid", "-C", dir}
	command := exec.Command("git", append(base, args...)...)
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
