package inventory_test

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/nnennandukwe/software-standards-bootstrap/internal/inventory"
	"github.com/nnennandukwe/software-standards-bootstrap/internal/workspace"
)

func TestScanBudgetsEveryCandidateBeforeContentExclusion(t *testing.T) {
	repo := newRepository(t)
	writeFile(t, filepath.Join(repo, "a-binary.dat"), "a\x00b")
	writeFile(t, filepath.Join(repo, "b-generated.go"), "// Code generated by fixture. DO NOT EDIT.\n")
	writeFile(t, filepath.Join(repo, "c-safe.txt"), "safe\n")
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "fixture")

	ws, err := workspace.OpenForInspect(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	report, err := inventory.Scan(context.Background(), ws, inventory.Limits{
		MaxCandidateFiles: 2,
		MaxCandidateBytes: 1 << 20,
		MaxFileBytes:      1 << 10,
	})
	if err != nil {
		t.Fatal(err)
	}

	if !report.Truncated {
		t.Fatalf("candidate file budget did not truncate report: %#v", report)
	}
	if len(report.Files) != 0 {
		t.Fatalf("over-budget safe file was read: %#v", report.Files)
	}
	if report.Excluded.Binary != 1 || report.Excluded.Generated != 1 {
		t.Fatalf("scanned content exclusions = %#v, want one binary and one generated", report.Excluded)
	}

	encoded, err := json.Marshal(report)
	if err != nil {
		t.Fatal(err)
	}
	var fields map[string]any
	if err := json.Unmarshal(encoded, &fields); err != nil {
		t.Fatal(err)
	}
	for key, want := range map[string]float64{
		"candidate_files":           3,
		"scanned_files":             2,
		"indexed_files":             0,
		"remaining_candidate_files": 1,
	} {
		if got := fields[key]; got != want {
			t.Errorf("%s = %#v, want %.0f", key, got, want)
		}
	}
}

func TestScanForPruneAllowsExistingCommittedPack(t *testing.T) {
	repo := newRepository(t)
	writeFile(t, filepath.Join(repo, "README.md"), "fixture\n")
	writeFile(t, filepath.Join(repo, ".software-standards", "assessment.md"), "assessment\n")
	writeFile(t, filepath.Join(repo, ".software-standards", "rules", "keep-me.md"), "rule\n")
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "adopt standards")

	ws, err := workspace.OpenForPrune(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	report, err := inventory.ScanForPrune(context.Background(), ws, inventory.DefaultLimits())
	if err != nil {
		t.Fatalf("prune scan rejected an adopted pack: %v", err)
	}
	if report.Truncated || report.BaselineCommit != ws.Baseline() {
		t.Fatalf("unexpected prune report: %#v", report)
	}
}

func TestScanIncludesExactCandidateByteBoundaryAndStopsBeforeNextBlob(t *testing.T) {
	repo := newRepository(t)
	writeFile(t, filepath.Join(repo, "a.txt"), "aa")
	writeFile(t, filepath.Join(repo, "b.dat"), "b\x00b")
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "fixture")

	ws, err := workspace.OpenForInspect(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	report, err := inventory.Scan(context.Background(), ws, inventory.Limits{
		MaxCandidateFiles: 10,
		MaxCandidateBytes: 2,
		MaxFileBytes:      1 << 10,
	})
	if err != nil {
		t.Fatal(err)
	}

	if !report.Truncated ||
		!strings.Contains(report.TruncationReason, "max_candidate_bytes=2") {
		t.Fatalf("byte truncation not disclosed: %#v", report)
	}
	if report.CandidateFiles != 2 || report.CandidateBytes != 5 ||
		report.ScannedFiles != 1 || report.ScannedBytes != 2 ||
		report.RemainingCandidateFiles != 1 || report.RemainingCandidateBytes != 3 {
		t.Fatalf("candidate accounting is inconsistent: %#v", report)
	}
	if len(report.Files) != 1 || report.Files[0].Path != "a.txt" {
		t.Fatalf("exact-boundary file was not indexed: %#v", report.Files)
	}
	if report.IndexedFiles != len(report.Files) {
		t.Fatalf("indexed_files = %d, want %d", report.IndexedFiles, len(report.Files))
	}
	if report.Excluded.Binary != 0 {
		t.Fatalf("over-budget binary blob was read: %#v", report.Excluded)
	}
}

func TestScanReportsFileLimitWhenFileAndByteBudgetsBothBlockNextCandidate(t *testing.T) {
	repo := newRepository(t)
	writeFile(t, filepath.Join(repo, "a.txt"), "aa")
	writeFile(t, filepath.Join(repo, "b.txt"), "bb")
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "fixture")

	ws, err := workspace.OpenForInspect(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	report, err := inventory.Scan(context.Background(), ws, inventory.Limits{
		MaxCandidateFiles: 1,
		MaxCandidateBytes: 2,
		MaxFileBytes:      1 << 10,
	})
	if err != nil {
		t.Fatal(err)
	}

	if report.TruncationReason != "inventory stopped at max_candidate_files=1" {
		t.Fatalf("truncation reason = %q, want file-limit precedence", report.TruncationReason)
	}
}

func TestDefaultLimitsAreDerivedFromTheSupportedBenchmarkEnvelope(t *testing.T) {
	limits := inventory.DefaultLimits()
	if limits.MaxCandidateFiles != 40_000 ||
		limits.MaxCandidateBytes != 128<<20 ||
		limits.MaxFileBytes != 1<<20 {
		t.Fatalf("default limits = %#v", limits)
	}
}

func TestScanIndexesOnlySafeTrackedRegularFilesAtTheBaseline(t *testing.T) {
	repo := newRepository(t)
	unicodePath := "docs/a\n日本語.md"
	shellPath := "docs/$([not-a-command]);*.txt"
	if runtime.GOOS == "windows" {
		// Win32 rejects newlines and asterisks in filenames. Keep every
		// equivalent edge case that the host filesystem can represent.
		unicodePath = "docs/a 日本語.md"
		shellPath = "docs/$([not-a-command]);.txt"
	}
	writeFile(t, filepath.Join(repo, "src", "main.go"), "package main\n\nfunc main() {}\n")
	writeFile(t, filepath.Join(repo, filepath.FromSlash(unicodePath)), "# Evidence\n")
	writeFile(t, filepath.Join(repo, filepath.FromSlash(shellPath)), "literal path\n")
	writeFile(t, filepath.Join(repo, "vendor", "ignored.go"), "package ignored\n")
	writeFile(t, filepath.Join(repo, ".env"), "TOKEN=do-not-read\n")
	writeFile(t, filepath.Join(repo, "large.txt"), strings.Repeat("x", 80))
	writeFile(t, filepath.Join(repo, "binary.dat"), "safe\x00not-text")
	writeFile(t, filepath.Join(repo, "generated.go"), "// Code generated by fixture. DO NOT EDIT.\n")
	if err := os.Symlink("../../outside", filepath.Join(repo, "src", "escape")); err != nil {
		t.Fatal(err)
	}
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "fixture")

	ws, err := workspace.OpenForInspect(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	report, err := inventory.Scan(context.Background(), ws, inventory.Limits{
		MaxCandidateFiles: 100,
		MaxCandidateBytes: 1 << 20,
		MaxFileBytes:      64,
	})
	if err != nil {
		t.Fatal(err)
	}

	gotPaths := make([]string, 0, len(report.Files))
	for _, file := range report.Files {
		gotPaths = append(gotPaths, file.Path)
		if !strings.HasPrefix(file.SHA256, "sha256:") {
			t.Fatalf("%s has non-canonical digest %q", file.Path, file.SHA256)
		}
	}
	wantPaths := []string{shellPath, unicodePath, "src/main.go"}
	if !reflect.DeepEqual(gotPaths, wantPaths) {
		t.Fatalf("paths = %#v, want %#v", gotPaths, wantPaths)
	}
	if report.Excluded.Binary != 1 || report.Excluded.Generated != 1 ||
		report.Excluded.Oversized != 1 || report.Excluded.SecretLike != 1 ||
		report.Excluded.Symlink != 1 || report.Excluded.VendorTree != 1 {
		t.Fatalf("unexpected exclusions: %#v", report.Excluded)
	}
	if report.BaselineCommit != ws.Baseline() {
		t.Fatalf("baseline = %q, want %q", report.BaselineCommit, ws.Baseline())
	}
}

func TestScanCountsSubmodulesWithoutDescendingIntoThem(t *testing.T) {
	child := newRepository(t)
	writeFile(t, filepath.Join(child, "child.txt"), "must not be inventoried\n")
	git(t, child, "add", "child.txt")
	git(t, child, "commit", "-m", "child")

	repo := newRepository(t)
	writeFile(t, filepath.Join(repo, "README.md"), "parent\n")
	git(t, repo, "-c", "protocol.file.allow=always", "submodule", "add", child, "deps/child")
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "parent with submodule")

	ws, err := workspace.OpenForInspect(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	report, err := inventory.Scan(context.Background(), ws, inventory.DefaultLimits())
	if err != nil {
		t.Fatal(err)
	}
	if report.Excluded.Submodule != 1 {
		t.Fatalf("submodule exclusion count = %d, want 1", report.Excluded.Submodule)
	}
	for _, file := range report.Files {
		if strings.HasPrefix(file.Path, "deps/child/") {
			t.Fatalf("inventory descended into submodule: %#v", report.Files)
		}
	}
}

func TestScanIsStableAndDisclosesResourceTruncation(t *testing.T) {
	repo := newRepository(t)
	writeFile(t, filepath.Join(repo, "z.txt"), "z\n")
	writeFile(t, filepath.Join(repo, "a.txt"), "a\n")
	git(t, repo, "add", ".")
	git(t, repo, "commit", "-m", "fixture")

	ws, err := workspace.OpenForInspect(context.Background(), repo)
	if err != nil {
		t.Fatal(err)
	}
	limits := inventory.Limits{MaxCandidateFiles: 1, MaxCandidateBytes: 1 << 20, MaxFileBytes: 1 << 10}
	first, err := inventory.Scan(context.Background(), ws, limits)
	if err != nil {
		t.Fatal(err)
	}
	second, err := inventory.Scan(context.Background(), ws, limits)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("same commit produced different reports:\n%#v\n%#v", first, second)
	}
	if !first.Truncated || !strings.Contains(first.TruncationReason, "max_candidate_files=1") {
		t.Fatalf("truncation not disclosed: %#v", first)
	}
	if len(first.Files) != 1 || first.Files[0].Path != "a.txt" {
		t.Fatalf("expected deterministic path ordering, got %#v", first.Files)
	}
}

func newRepository(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	git(t, dir, "init", "-b", "main")
	return dir
}

func git(t *testing.T, dir string, args ...string) string {
	t.Helper()
	command := append([]string{"-c", "user.name=SSB Test", "-c", "user.email=ssb@example.invalid", "-C", dir}, args...)
	cmd := exec.Command("git", command...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s failed: %v\n%s", strings.Join(args, " "), err, out)
	}
	return string(out)
}

func writeFile(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
